apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elasticsearch-operator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: elasticsearch-operator
    spec:
      containers:
      - name: operator
        image: registry.namely.run/namely/elasticsearch-operator:0.0.5
        imagePullPolicy: Always
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      - name: kubectl
        image: kelseyhightower/kubectl:1.3.4
        args:
          - "proxy"
      imagePullSecrets:
        - name: namely-nonproduction-pull-secret
